### ISSUE TITLE
Adding a setup.py for the package installation

### ISSUE THREAD

**Issue by hokanoei** [PeterTKovacs/boxes#8]
Hi and thanks for having shared this package. I am exploring the computational time of the memb in python and I was considering trying running your script. However, when installing the package I get the error "ERROR: File "setup.py" not found for legacy project git+https://github.com/PeterTKovacs/boxes.git." Could you add some lines in the readme file on how to run the package? Thanks.

**Comment by marcessz** [comment]
Hi!
Currently, it does not work as an installable Python package. We are planning to develop a package that can be installed using pip and conda. Now you can use the codes by downloading the repository and then import the boxes folder as it can be seen in the tutorial notebook: https://github.com/PeterTKovacs/boxes/blob/main/tutorial/boxing_tutorial.ipynb

**Comment by hokanoei** [comment]
I see, thanks!
